"""cria tabela produtos

Revision ID: 02111b5ba41c
Revises: 5081a998b8ce
Create Date: 2026-03-24 18:18:16.479367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02111b5ba41c'
down_revision = '5081a998b8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margem_lucro', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
