"""cria tabela entidades

Revision ID: 5081a998b8ce
Revises: 3dff3a67f32a
Create Date: 2026-03-24 17:54:23.581282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5081a998b8ce'
down_revision = '3dff3a67f32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_entidade', sa.String(length=20), nullable=False),
    sa.Column('nome_razao_social', sa.String(length=180), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=180), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('cep', sa.String(length=12), nullable=True),
    sa.Column('logradouro', sa.String(length=180), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entidades')
    # ### end Alembic commands ###
