"""cria tabela plano_contas

Revision ID: da6ea0a337e5
Revises: 02111b5ba41c
Create Date: 2026-03-24 18:31:58.392880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6ea0a337e5'
down_revision = '02111b5ba41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False),
    sa.Column('natureza', sa.String(length=20), nullable=False),
    sa.Column('conta_pai_id', sa.Integer(), nullable=True),
    sa.Column('aceita_lancamento', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_pai_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plano_contas')
    # ### end Alembic commands ###
